import logo from "./logo-grey.png";
import "./App.css";
import pachina from "./pachaFinal.pdf";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <div id="report" class="register-box-body">
          <p class="login-box-msg">Laboratory Result</p>{" "}
          <div class="box-header with-border">
            <h3 class="box-title">Animal</h3>
          </div>{" "}
          <div class="box-body">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td>
                    <b>Animal species</b>
                  </td>{" "}
                  <td>DOG</td>
                </tr>{" "}
                <tr>
                  <td>
                    <b>Microchip number</b>
                  </td>{" "}
                  <td>941010000775883</td>
                </tr>{" "}
                <tr>
                  <td>
                    <b>Sex</b>
                  </td>{" "}
                  <td>FEMALE</td>
                </tr>{" "}
                <tr>
                  <td>
                    <b>Date of birth</b>
                  </td>{" "}
                  <td>10/10/2022</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="box-header with-border">
            <h3 class="box-title">Report</h3>
          </div>{" "}
          <div class="box-body">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td>
                    <b>Report date</b>
                  </td>{" "}
                  <td>14/04/2023</td>
                </tr>{" "}
                <tr>
                  <td>
                    <b>Material</b>
                  </td>{" "}
                  <td>BLOOD SERUM</td>
                </tr>{" "}
                <tr>
                  <td>
                    <b>RABIES ANTIBODY TITRATION</b>
                  </td>{" "}
                  <td>greater or equal to 0.5 IU/ml </td>
                </tr>
              </tbody>
            </table>
          </div>{" "}
          <div class="row">
            <div class="col-xs-12">
              <a href={pachina} class="btn btn-primary btn-block btn-flat">
                Download report (pdf format)
              </a>
            </div>
          </div>
        </div>
        <div class="credentials-div">
          <p class="credentials">
            This report was generated by&nbsp;
            <a href="https://www.izsvenezie.it/" target="_blank">
              Istituto Zooprofilattico delle Venezie
            </a>
            &nbsp;and is blockchain certified by&nbsp;
            <a href="https://projectesse.org" target="_blank">
              ESSE Tech
            </a>
            .
          </p>
        </div>
      </header>
    </div>
  );
}

export default App;
